### ISSUE TITLE
Missing <association> element in reference (DB 5.2)?

### ISSUE THREAD

**Issue by tomschr** [docbook/defguide#80]
# Problem

According to the DocBook RNG schema, there is an association element defined:

```
  db.association =
    ## Identifies the type of relationship between one or more resources
    element association { db.association.attlist, text? }
```

However, the reference at https://tdg.docbook.org/tdg/5.2/ref-elements.html never mentions that.

# Possible solution

Add the missing element into the reference. :wink:

**Comment by tomschr** [comment]
Ahh, thanks Norm! However, I've tried to access it from the **TOC** and it's not there:

![toc-without-association](https://user-images.githubusercontent.com/1312925/127662563-c4795f20-b168-4338-86a2-c7877a531d5d.png)

**Comment by ndw** [comment]
Scroll down further: 

<img width="1010" alt="Screen Shot 2021-07-30 at 3 11 30 PM" src="https://user-images.githubusercontent.com/36793/127665747-3cf6689a-5bc5-426c-a206-3c6e9b2b16a9.png">

Maybe having them in a different part is more confusing rather than less?

**Comment by tomschr** [comment]
Argh. I feel so stupid now. :laughing: Sorry, for the noise.

> Maybe having them in a different part is more confusing rather than less?

I think it's fine the way it is. This element is not available in normal DocBook schema, only in the assembly. So it's ok. It was my fault. I've searched in the browser, but for some reason it didn't show up. 

Thanks Norm! Closing it.
